dist: bionic
language: php

php:
  - 7.3

before_install:
  - pecl install ast
install:
  - composer install

before_script: skip
script:
  - ./vendor/bin/phan
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix . --dry-run
